---
abstract: 'Lookup states and capitals by state names or abbreviations'
author:
  - 'Curtis Brandt <curtis@cpan.org>'
build_requires:
  Test::More: '0.96'
  Test::NoWarnings: '1.03'
configure_requires:
  Module::Build::Tiny: '0.036'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Geo-States
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: '5.008005'
resources:
  bugtracker: https://github.com/aggrolite/Geo-States/issues
  homepage: https://github.com/aggrolite/Geo-States
  repository: https://github.com/aggrolite/Geo-States.git
version: '0.02'
